spring.application.name=demo

# C?u hình k?t n?i SQL Server
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=CourseRegistrationDB_J2EE;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=123
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver

# C?u hình JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServer2016Dialect

# Google OAuth2 (Thay thông s? c?a b?n sau khi ??ng ký trên Google Console)
spring.security.oauth2.client.registration.google.client-id=632983918188-jijcr9pcovnig31id6iv8jneoscpsvj.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=profile,email

server.servlet.encoding.charset=UTF-8
server.servlet.encoding.force=true
spring.thymeleaf.encoding=UTF-8